### ISSUE TITLE
object_walker does not work with systemd 

### ISSUE THREAD

**Issue by sigbjornaib** [pemcg/object_walker#10]
As ManageIQ is now logging to systemd, object_walker fails as there is no automation.log to read.

**Comment by pemcg** [comment]
I haven't tested object_walker with systemd, but I'd have thought that the log lines are still written but the object_walker_reader can no longer be used to extract the dumps. Is this correct?

**Comment by sigbjornaib** [comment]
The log files are no longer present at the location:


```
# object_walker_reader.rb
Error opening log file: No such file or directory @ rb_sysopen - /var/www/miq/vmdb/log/automation.log

# ls -la /var/www/miq/vmdb/log/automation.log
ls: cannot access '/var/www/miq/vmdb/log/automation.log': No such file or directory

```

It would seem like they are only present inside systemd (systemd-journald) now.

**Comment by pemcg** [comment]
Unfortunately object_walker isn't developed any more, but I'd suggest using a combination of journalctl and grep, or something like that.
