### ISSUE TITLE
Error  walking 'network_routers'

### ISSUE THREAD

**Issue by vaclavmiller** [pemcg/object_walker#4]
Hello, when using objectWalker 1.7 I had error in evm.log:
[----] E, [2016-06-08T22:48:42.566148 #3082:65aeff0] ERROR -- : <AutomationEngine> The following error occurred during instance method <private_networks> for AR object <#<ManageIQ::Providers::Openstack::CloudManager::CloudNetwork::Private id: 50000000000015, name: "private", ems_ref: "d1199eee-2a23-49d8-bc37-b3fe508bfa26", ems_id: 50000000000009, cidr: nil, status: "active", enabled: true, external_facing: false, cloud_tenant_id: 50000000000001, orchestration_stack_id: nil, shared: false, provider_physical_network: nil, provider_network_type: nil, provider_segmentation_id: nil, vlan_transparent: nil, extra_attributes: {:maximum_transmission_unit=>0, :port_security_enabled=>nil}, type: "ManageIQ::Providers::Openstack::CloudManager::Clou...">>
[----] E, [2016-06-08T22:48:42.566921 #3082:65aeff0] ERROR -- : <AutomationEngine> MiqAeServiceModelBase.ar_method raised: <NoMethodError>: <undefined method `private_networks' for #<ManageIQ::Providers::Openstack::CloudManager::CloudNetwork::Private:0x0000000dc3a4a8>>
[----] E, [2016-06-08T22:48:42.567150 #3082:65aeff0] ERROR -- : <AutomationEngine> /opt/rh/cfme-gemset/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:433:in `method_missing'

In ObjectWalker output there were messages:
**\* not walking: 'network_routers' isn't in the @walk_association_whitelist hash for MiqAeServiceManageIQ_Providers_Openstack_CloudManager_CloudNetwork_Private ***
     |    |    |    /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:242:in `block in object_send'
     |    |    |    /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:261:in`ar_method'
     |    |    |    /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:271:in `ar_method'
     |    |    |    /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:240:in`object_send'
     |    |    |    /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:93:in `block (2 levels) in expose'
     |    |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1624:in`perform_without_block'
     |    |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1584:in `perform'
     |    |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1657:in`block (2 levels) in main_loop'
     |    |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1653:in `loop'
     |    |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1653:in`block in main_loop'

Please may you check?
Kind regards,
Vaclav

**Comment by pemcg** [comment]
Hi Vaclav

Thanks for reporting this. I think that CloudForms has skipped the 'network_routers' association (you get the message "**\* not walking: 'network_routers' isn't in the @walk_association_whitelist hash for MiqAeServiceManageIQ_Providers_Openstack_CloudManager_CloudNetwork_Private ***"), and is failing on the next association which is 'private_networks'.

I believe you're seeing this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1332043 in CloudForms, which looks like it's been fixed and will be in an update to CFME 5.5

Many thanks,
Peter

**Comment by vaclavmiller** [comment]
Hi Peter, 

thanks for checking reported issue. 
And for ObjectWalker and your CFME docs as well. I found it very useful although I still sometimes feel lost in CFME automation model :-) 

Kind regards, 
Vaclav
