### ISSUE TITLE
Feature Request: Print out custom_key/value pairs on objects

### ISSUE THREAD

**Issue by nmaludy** [pemcg/object_walker#5]
Objects like the 'vm' and 'host' have the ability to set custom options using custom_set() and can be retrieved using custom_keys() and custom_get().

It would be great if object_walker would print these out to the log.

Something like:
  keys = vm.custom_keys
  keys.each do |key|
    value = vm.custom_get(key)
    $evm.log(:info, "custom key[#{key}] = #{value}")
  end

**Comment by pemcg** [comment]
Hi, thanks, that's a great idea. I have a few updates to object_walker that I need to do, and I'll add this to the list and hopefully get it done in the next few days.

**Comment by pemcg** [comment]
Implemented in v1.8
