### ISSUE TITLE
root['vm'].miq_provision is not being walked

### ISSUE THREAD

**Issue by nmaludy** [pemcg/object_walker#6]
In the latest version of object_walker.rb root['vm'].miq_provision was not being walked with the following error message:

```
     |    |    $evm.root['vm'].miq_provision (type: Association)
     |    |    *** not walking: 'miq_provision' isn't in the walk_association_whitelist hash for MiqAeServiceManageIQ_Providers_Vmware_InfraManager_Vm ***
```

miq_provision was printed out by default in older versions of object_walker.rb

In order to remedy this i had to add 'miq_provision' to the the whitelists for MiqAeServiceManageIQ_Providers_Vmware_InfraManager_Vm and MiqAeServiceManageIQ_Providers_Redhat_InfraManager_Vm

```
'MiqAeServiceManageIQ_Providers_Vmware_InfraManager_Vm': ['ems_cluster', 'ems_folder', 'resource_pool', 'ext_management_system', 'storage', 'service', 'hardware', 'operating_system', 'miq_provision'],
'MiqAeServiceManageIQ_Providers_Redhat_InfraManager_Vm': ['ems_cluster', 'ems_folder', 'resource_pool', 'ext_management_system', 'storage', 'service', 'hardware', 'operating_system', 'miq_provision'],
```

With the modified whitelist i get the following:

```
     |    |    $evm.root['vm'].miq_provision (type: Association)
     |    |    miq_provision = $evm.root['vm'].miq_provision
     |    |    (object type: MiqAeServiceManageIQ_Providers_Vmware_InfraManager_Provision, object ID: 1000000000092)
     |    |    |    --- attributes follow ---
```

Does this seem right? Could this be a bug in the new code, or maybe a bug in the old code that got fixed?

**Comment by pemcg** [comment]
Hi

It certainly would have been a bug before if it was walking an association that wasn't in the whitelist, but I'm not aware of fixing anything like that.

What you may have seen previously is object_walker dumping the provisioning task directly from $evm.root['miq_provision']. This would always be traversed as it's not an association from another service model object, but accessible directly from $evm.root.
