### ISSUE TITLE
Walk stalls in MiqAeServiceManageIQ_Providers_Vmware_InfraManager

### ISSUE THREAD

**Issue by mlbrianr** [pemcg/object_walker#7]
I am running object_walker from a button on a VMware provider.   I am running CloudForms 5.6.2.2.  When I do so, the walk consistently stalls at the same point, and a few minutes later, CloudForms terminates the process.

Could you help me figure out what might be going on here?   I've included a log snippet and can provide other information as necessary.  Thanks..

     |    |    $evm.root['ext_management_system'].total_miq_templates = 26   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_storages = 34   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_subnets = 0   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_vms = 754   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_vms_and_templates = 780   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_vms_never = 0   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_vms_off = 28   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_vms_on = 722   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_vms_suspended = 4   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].total_vms_unknown = 0   (type: Fixnum)
     |    |    $evm.root['ext_management_system'].zone_name = default   (type: String)
     |    |    --- end of virtual columns ---
     |    |    --- associations follow ---
     |    |    $evm.root['ext_management_system'].customization_specs (type: Association)
     |    |    *** not walking: 'customization_specs' isn't in the walk_association_whitelist hash for MiqAeServiceManageIQ_Providers_Vmware_InfraManager ***
     |    |    $evm.root['ext_management_system'].ems_clusters (type: Association)
     |    |    *** not walking: 'ems_clusters' isn't in the walk_association_whitelist hash for MiqAeServiceManageIQ_Providers_Vmware_InfraManager ***
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:574:in `load'
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:640:in `recv_reply'
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:940:in `recv_reply'
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1254:in `send_message'
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1142:in `block (2 levels) in method_missing'
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1229:in `open'
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1141:in `block in method_missing'
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1160:in `with_friend'
     |    |    /opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1140:in `method_missing'
     |    |    <code: associated_objects = Array.wrap(this_object.method_missing(:send, association))>:410:in `block in print_associations'
     |    |    <code: associations.uniq.sort.each do |association|>:408:in `each'
     |    |    <code: associations.uniq.sort.each do |association|>:408:in `print_associations'
     |    |    <code: print_associations(object_string, this_object, this_object_class)>:681:in `walk_object'
     |    |    <code: walk_object("#{object_string}[\'#{attribute_name}\']", attribute_value)>:190:in `block in print_attributes'
     |    |    <code: this_object.attributes.keys.sort.each do |attribute_name|>:183:in `each'
     |    |    <code: this_object.attributes.keys.sort.each do |attribute_name|>:183:in `print_attributes'
     |    |    <code: print_attributes(object_string, this_object)>:679:in `walk_object'

**Comment by pemcg** [comment]
Hi, thanks for bringing this to my attention. Could you please paste the next 20-25 lines of the log as well? (I'd like to see the complete stack trace).

Also, which version of object_walker are you running?

Many thanks,
pemcg

**Comment by mlbrianr** [comment]
I've attached the next several lines in the log.  It seemed as though that was the end of that stack trace, although there is a bunch of other stuff which could be related.   

I was running 1.9 originally and installed 1.9.2 earlier this week to see if there were any updates which made a difference.
Thanks..

[object-walker-log-20161130.txt](https://github.com/pemcg/object_walker/files/628351/object-walker-log-20161130.txt)

**Comment by pemcg** [comment]
Hi, thanks for that. This is interesting, clearly something is preventing object_walker from continued running, and the automation engine is killing the method at the 10 minute time limit. Can you send me the first 30 or so lines from the object_walker_reader output? This will show me the whitelist and context of calling (object hierarchy). Feel free to email to pemcg@redhat.com if you'd prefer, rather than pasting here. It might be worth defining a whitelist entry for 'MiqAeServiceManageIQ_Providers_Vmware_InfraManager':['ALL'] to see whether this changes the behaviour at all.

I have seen object_walker hang occasionally when the `$print_evm_parent` variable was set to `true`, but you're still dumping $evm.root so I don't think this is the same problem. The only difference between 1.9.1 and 1.9.2 was to default this to `false`. I'll look further into how I can troubleshoot what the engine is doing.
